In [1]:
import tensorflow as tf
import torch

In [4]:
x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]
y_data = [152.,185.,180.,196.,142.]
x1= tf.placeholder(tf.float32)
x2= tf.placeholder(tf.float32)
x3= tf.placeholder(tf.float32)
Y  = tf.placeholder(tf.float32)

In [5]:
w1 = tf.Variable(tf.random_normal([1]), name = "weight1")
w2 = tf.Variable(tf.random_normal([1]), name = "weight2")
w3 = tf.Variable(tf.random_normal([1]), name = "weight3")
b = tf.Variable(tf.random_normal([1]), name = "bias")
hypothesis = x1 * w1 + x2 * w3 * w3 * b

In [6]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {x1: x1_data,x2: x2_data,x3: x3_data, Y: y_data})
    if step %10 ==0:
        print(step, "cost: ", cost_val, "\nPrediction:\n", hy_val)

0 cost:  25640.3 
Prediction:
 [  5.88110733  16.31036377  11.31005859  12.29927444  14.75117493]
10 cost:  377.779 
Prediction:
 [ 130.739151    166.88777161  159.54908752  172.10162354  131.07077026]
20 cost:  26.8743 
Prediction:
 [ 143.94030762  183.61207581  175.59970093  189.41357422  144.17776489]
30 cost:  13.6163 
Prediction:
 [ 146.49897766  186.85609436  178.71182251  192.77030945  146.72067261]
40 cost:  13.1006 
Prediction:
 [ 147.00218201  187.49308777  179.32341003  193.4299469   147.2197876 ]
50 cost:  13.0771 
Prediction:
 [ 147.10183716  187.61813354  179.44400024  193.55999756  147.31752014]
60 cost:  13.0727 
Prediction:
 [ 147.12203979  187.64239502  179.46792603  193.58580017  147.33624268]
70 cost:  13.0692 
Prediction:
 [ 147.1265564   187.64677429  179.47279358  193.59103394  147.33937073]
80 cost:  13.0656 
Prediction:
 [ 147.12799072  187.6472168   179.47390747  193.59220886  147.33943176]
90 cost:  13.0621 
Prediction:
 [ 147.12876892  187.64689636  179.4742

830 cost:  12.8598 
Prediction:
 [ 147.16722107  187.61784363  179.48448181  193.60270691  147.29882812]
840 cost:  12.8577 
Prediction:
 [ 147.16766357  187.61756897  179.48461914  193.6028595   147.29844666]
850 cost:  12.8557 
Prediction:
 [ 147.16804504  187.61727905  179.48471069  193.60295105  147.29801941]
860 cost:  12.8536 
Prediction:
 [ 147.16845703  187.61700439  179.48484802  193.60308838  147.29762268]
870 cost:  12.8515 
Prediction:
 [ 147.16886902  187.61671448  179.48497009  193.60321045  147.29724121]
880 cost:  12.8495 
Prediction:
 [ 147.16925049  187.6164093   179.48506165  193.60328674  147.29681396]
890 cost:  12.8474 
Prediction:
 [ 147.16958618  187.61605835  179.48510742  193.60333252  147.2963562 ]
900 cost:  12.8454 
Prediction:
 [ 147.16999817  187.61579895  179.48522949  193.60346985  147.29597473]
910 cost:  12.8434 
Prediction:
 [ 147.17037964  187.61550903  179.48535156  193.60357666  147.29559326]
920 cost:  12.8414 
Prediction:
 [ 147.17079163  187.61

 [ 147.19308472  187.59840393  179.49142456  193.60961914  147.27200317]
1670 cost:  12.7237 
Prediction:
 [ 147.19334412  187.59825134  179.49151611  193.60969543  147.27177429]
1680 cost:  12.7225 
Prediction:
 [ 147.19358826  187.59809875  179.49157715  193.60977173  147.27153015]
1690 cost:  12.7213 
Prediction:
 [ 147.19381714  187.59791565  179.49163818  193.60983276  147.27130127]
1700 cost:  12.7201 
Prediction:
 [ 147.19406128  187.5977478   179.49169922  193.60990906  147.27105713]
1710 cost:  12.7189 
Prediction:
 [ 147.19429016  187.59757996  179.49179077  193.60998535  147.27082825]
1720 cost:  12.7177 
Prediction:
 [ 147.19451904  187.59741211  179.49183655  193.61003113  147.27058411]
1730 cost:  12.7165 
Prediction:
 [ 147.19471741  187.59719849  179.49185181  193.61006165  147.27032471]
1740 cost:  12.7153 
Prediction:
 [ 147.19490051  187.59700012  179.49188232  193.6100769   147.27005005]
1750 cost:  12.7142 
Prediction:
 [ 147.19514465  187.59684753  179.49197388  1